name: go2pro-enexis-ros2-desktop

services: 
  devcontainer-humble:
    volumes: 
      #- ..:/workspace:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /mnt/wslg:/mnt/wslg
      - /root/.gazebo/models/:/root/.gazebo/models/
      - /var/run/docker.sock:/var/run/docker.sock 
      - $HOME/.Xauthority:/tmp/.Xauthority:rw
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.Xauthority
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - CYCLONEDDS_URI=<CycloneDDS><Domain><General><Interfaces>
                            <NetworkInterface name="wlp9s0" priority="default" multicast="default" />
                        </Interfaces></General></Domain></CycloneDDS>
    cap_add:
      - SYS_PTRACE  
    command: /bin/sh -c "while sleep 1000; do :; done"
 
    build:
      context: .
      dockerfile: Dockerfile-humble
    # image: ros2-humble-dev:latest
    
    privileged: true
    network_mode: "host"
